// Generated by ios/scripts/export_menu_reference.py from Android menu sources.
import Foundation

struct GuideRole: Codable, Identifiable, Sendable {
    let id, title, story, image, advice, function, team: String
    let minimum: Int
}
struct GuideMap: Codable, Identifiable, Sendable {
    let id, title, shortTitle, era, description, image, exclusive: String
    let roles: [GuideRole]
}
struct HelpSectionContent: Codable, Identifiable, Sendable {
    let id, title, body: String
}
struct TutorialContent: Codable, Identifiable, Sendable {
    let id, title, body, hint: String
}
struct ProfileAchievementContent: Codable, Identifiable, Sendable {
    let id, title, shortTitle, description, rarity: String
}
struct ProfileEmoteContent: Codable, Identifiable, Sendable {
    let id, title, description, theme, image, category: String
    let premium, animated: Bool
}
enum AndroidMenuReference {
    struct Content: Codable, Sendable {
        let maps: [GuideMap]
        let help: [HelpSectionContent]
        let tutorial: [TutorialContent]
        let achievements: [ProfileAchievementContent]
        let emotes: [ProfileEmoteContent]
    }
    static let content = try! JSONDecoder().decode(Content.self, from: Data(json.utf8))
    private static let json = #"""
{
  "maps": [
    {
      "id": "medieval",
      "title": "Feudo de Hierro",
      "shortTitle": "Feudo",
      "era": "Epoca Medieval",
      "description": "Un feudo que aparenta paz mientras una familia misteriosa compra voluntades y siembra muertes discretas. El alcalde se aferra al poder entre banquetes, paranoia y ordenes que apenas recuerda.",
      "image": "mapa_medieval",
      "exclusive": "Bufón",
      "roles": [
        {
          "id": "aldeano",
          "title": "Aldeana",
          "story": "Vive donde el barro llega antes que las noticias. No tiene poder, título ni espada, pero conoce cada puerta, cada deuda y cada silencio raro del pueblo. Cuando el feudo empieza a pudrirse, ella lo nota antes que nadie.",
          "image": "rol_aldeano_medieval",
          "advice": "No tienes acción nocturna. Usa el debate: pregunta, compara versiones y recuerda quién acusó, defendió o cambió su historia.",
          "function": "No tiene habilidad especial. Participa en el debate y en las votaciones para descubrir a los traidores.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "policia",
          "title": "Detective",
          "story": "Antes resolvía robos menores y mentiras de taberna. Ahora sigue rastros de sangre disfrazados de accidentes, sabiendo que descubrir la verdad no sirve de nada si no vive lo suficiente para contarla.",
          "image": "rol_detective_medieval",
          "advice": "Cada noche investiga a un jugador. Guarda tus pistas hasta que puedas usarlas sin exponerte demasiado pronto.",
          "function": "Cada noche investiga a un jugador y recibe una pista sobre si parece inocente o sospechoso.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "medico",
          "title": "Médico",
          "story": "Todos en el feudo le deben algo: una fiebre curada, una herida cerrada o una vida salvada a tiempo. No pregunta de qué lado viene el paciente, pero recuerda cada corte, cada veneno y cada mentira.",
          "image": "rol_medico_medieval",
          "advice": "Cada noche protege a un jugador. Puedes protegerte si necesitas sobrevivir, o cuidar a quien tenga información clave.",
          "function": "Cada noche protege a un jugador. Si ese jugador iba a morir, la eliminación se cancela.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "alcalde",
          "title": "Alcalde",
          "story": "Gobierna desde una silla demasiado grande y un salón demasiado lleno. Está perdiendo la cordura entre rumores, copas servidas y órdenes que apenas recuerda, pero todavía conserva el poder de salvar o condenar al feudo.",
          "image": "rol_alcalde_medieval",
          "advice": "Puedes revelarte durante el debate. Desde entonces tu voto vale doble y puedes decidir empates.",
          "function": "Puede revelar su identidad durante el debate. Desde ese momento su voto vale doble y decide entre los dos participantes más votados si hay empate.",
          "minimum": 8,
          "team": "Pueblo"
        },
        {
          "id": "asesino",
          "title": "Asesino",
          "story": "Una familia misteriosa lo compró con oro, tierras y promesas de un apellido respetado. No mata por fe ni por justicia: mata porque vio una escalera hacia el poder y decidió subirla con las manos manchadas.",
          "image": "rol_asesino_medieval",
          "advice": "Cada noche elige una víctima con los Traidores. De día, desvía sospechas sin defender siempre a tus aliados.",
          "function": "Los asesinos eligen en conjunto una víctima durante la noche. Si queda uno solo, decide por su cuenta.",
          "minimum": 5,
          "team": "Traidores"
        },
        {
          "id": "espia",
          "title": "Espía",
          "story": "Aconseja al alcalde desde muy cerca, eligiendo qué verdades llegan completas y cuáles llegan torcidas. Su arma no es una daga, sino una voz tranquila que alimenta la paranoia del poder.",
          "image": "rol_espia_medieval",
          "advice": "El investigador te verá como inocente. Participa en la elección de víctima y usa esa apariencia para proteger a los Traidores.",
          "function": "Elige la víctima cada noche junto a los asesinos, pero ante la investigación aparece como inocente.",
          "minimum": 10,
          "team": "Traidores"
        },
        {
          "id": "mercenario",
          "title": "Mercenario",
          "story": "No sirve a ningún linaje, solo al contrato correcto. Ha peleado por señores que olvidaron su nombre y ahora cobra para que ciertas conversaciones terminen antes de tiempo.",
          "image": "rol_mercenario_medieval",
          "advice": "Cada noche silencia a un jugador. Elige a quien pueda convencer al pueblo o compartir información importante.",
          "function": "Forma parte del bando traidor. Puede impedir que una víctima hable o vote durante el día siguiente.",
          "minimum": 7,
          "team": "Traidores"
        },
        {
          "id": "desertor",
          "title": "Desertora",
          "story": "Una vez juró proteger el feudo, hasta que entendió a quién estaba protegiendo realmente. Desde entonces vive entre caminos y nombres falsos, cargando con la duda de si huyó por cobardía o por lucidez.",
          "image": "rol_desertor_medieval",
          "advice": "Elige un bando y ayuda a que gane. Sobrevivir importa: no te comprometas sin mirar quién tiene ventaja.",
          "function": "Elige un bando al comenzar. Puede reconsiderarlo una sola vez cuando quedan aproximadamente dos tercios de los jugadores iniciales y debe sobrevivir para ganar con su bando final.",
          "minimum": 14,
          "team": "Neutral"
        },
        {
          "id": "bufon",
          "title": "Bufón",
          "story": "Molesta, interrumpe y se esfuerza por caer mal. Mientras el feudo se hunde en acusaciones, exagera, provoca y dice lo necesario para que todos quieran expulsarlo. Solo gana si el pueblo lo elimina durante la votación.",
          "image": "rol_bufon_medieval",
          "advice": "No actúas de noche. Tu objetivo es que el pueblo te expulse durante la votación, no morir de noche.",
          "function": "Molesta, interrumpe y busca hacerse odiar para que el pueblo lo expulse durante la votación. Esa es su única condición de victoria: no gana si muere de noche ni por otra causa.",
          "minimum": 8,
          "team": "Neutral"
        }
      ]
    },
    {
      "id": "grecia",
      "title": "Antigua Grecia",
      "shortTitle": "Grecia",
      "era": "Siglo V a.C.",
      "description": "Una polis pequeña obsesionada con parecer grande. En la plaza, los discursos de honor esconden hambre, deudas y un culto popular que mata con máscaras doradas en nombre de Ares.",
      "image": "mapa_grecia",
      "exclusive": "Oráculo",
      "roles": [
        {
          "id": "aldeano",
          "title": "Aldeano",
          "story": "Vende aceite, pan o telas bajo estatuas demasiado grandes para una ciudad tan pequeña. Escucha a los hombres hablar de gloria en la plaza mientras ella cuenta monedas para llegar al invierno. No cree en discursos: cree en sobrevivir al próximo decreto.",
          "image": "rol_aldeano_griego",
          "advice": "No tienes acción nocturna. Usa el debate: pregunta, compara versiones y recuerda quién acusó, defendió o cambió su historia.",
          "function": "No tiene habilidad especial. Participa en el debate y en las votaciones para descubrir a los traidores.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "policia",
          "title": "Detective",
          "story": "No busca huellas en callejones, sino contradicciones en discursos públicos. Sabe que en la polis nadie miente en silencio: todos mienten frente a testigos, con palabras hermosas y las manos limpias.",
          "image": "rol_detective_griego",
          "advice": "Cada noche investiga a un jugador. Guarda tus pistas hasta que puedas usarlas sin exponerte demasiado pronto.",
          "function": "Cada noche investiga a un jugador y recibe una pista sobre si parece inocente o sospechoso.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "medico",
          "title": "Médico",
          "story": "Aprendió a curar cuerpos entrenados para la guerra y estómagos vacíos por culpa de la política. Ante sus manos no importa si alguien invoca a Ares, a Atenea o a nadie; la sangre se seca igual en todos.",
          "image": "rol_medico_griego",
          "advice": "Cada noche protege a un jugador. Puedes protegerte si necesitas sobrevivir, o cuidar a quien tenga información clave.",
          "function": "Cada noche protege a un jugador. Si ese jugador iba a morir, la eliminación se cancela.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "alcalde",
          "title": "Alcalde",
          "story": "No gobierna desde un trono, sino desde la palabra. Cada decisión debe sonar justa, fuerte y digna ante una polis que exige grandeza aunque apenas pueda sostenerse. Su miedo no es morir: es quedar como el líder que hizo pequeña a su ciudad.",
          "image": "rol_alcalde_griego",
          "advice": "Puedes revelarte durante el debate. Desde entonces tu voto vale doble y puedes decidir empates.",
          "function": "Puede revelar su identidad durante el debate. Desde ese momento su voto vale doble y decide entre los dos participantes más votados si hay empate.",
          "minimum": 8,
          "team": "Pueblo"
        },
        {
          "id": "asesino",
          "title": "Asesina",
          "story": "Se puso la máscara dorada para dejar de ser una voz ignorada entre la multitud. El culto le prometió que Ares no escucha plegarias, escucha actos. Desde entonces mata convencida de que cada cuerpo caído obliga a la polis a despertar.",
          "image": "rol_asesino_griego",
          "advice": "Cada noche elige una víctima con los Traidores. De día, desvía sospechas sin defender siempre a tus aliados.",
          "function": "Los asesinos eligen en conjunto una víctima durante la noche. Si queda uno solo, decide por su cuenta.",
          "minimum": 5,
          "team": "Traidores"
        },
        {
          "id": "espia",
          "title": "Espía",
          "story": "No necesita ocultarse en sombras: se sienta en la plaza, aplaude discursos y repite frases en el oído correcto. En una ciudad gobernada por reputaciones, una palabra bien colocada puede arruinar más que una daga.",
          "image": "rol_espia_griego",
          "advice": "El investigador te verá como inocente. Participa en la elección de víctima y usa esa apariencia para proteger a los Traidores.",
          "function": "Elige la víctima cada noche junto a los asesinos, pero ante la investigación aparece como inocente.",
          "minimum": 10,
          "team": "Traidores"
        },
        {
          "id": "mercenario",
          "title": "Mercenario",
          "story": "Vino de guerras ajenas, donde los dioses cambiaban de nombre pero los muertos pesaban igual. La polis lo mira como extranjero útil: indigno para votar, perfecto para hacer lo que ningún ciudadano quiere admitir.",
          "image": "rol_mercenario_griego",
          "advice": "Cada noche silencia a un jugador. Elige a quien pueda convencer al pueblo o compartir información importante.",
          "function": "Forma parte del bando traidor. Puede impedir que una víctima hable o vote durante el día siguiente.",
          "minimum": 7,
          "team": "Traidores"
        },
        {
          "id": "desertor",
          "title": "Desertor",
          "story": "Abandonó la defensa de la polis cuando entendió que sus murallas protegían más orgullo que vidas. No traicionó una bandera; se negó a morir por discursos escritos por hombres que nunca pisan el campo de batalla.",
          "image": "rol_desertor_griego",
          "advice": "Elige un bando y ayuda a que gane. Sobrevivir importa: no te comprometas sin mirar quién tiene ventaja.",
          "function": "Elige un bando al comenzar. Puede reconsiderarlo una sola vez cuando quedan aproximadamente dos tercios de los jugadores iniciales y debe sobrevivir para ganar con su bando final.",
          "minimum": 14,
          "team": "Neutral"
        },
        {
          "id": "oraculo",
          "title": "Oráculo",
          "story": "La respetan porque habla con lo que nadie puede controlar. Pero su don no obedece a la política ni al deseo del pueblo: puede traer de vuelta una verdad salvadora o una voz que incendie la ciudad desde la tumba.",
          "image": "rol_oraculo_griego",
          "advice": "Actúas de noche. Una vez por partida puedes invocar a un muerto para que hable en el próximo debate.",
          "function": "Una vez por partida puede invocar a cualquier jugador muerto para el debate del día siguiente. Su rol permanece oculto: puede hablar, pero no votar ni usar habilidades.",
          "minimum": 8,
          "team": "Pueblo"
        }
      ]
    },
    {
      "id": "pampa",
      "title": "Pueblo del Interior - 1915",
      "shortTitle": "Pampa",
      "era": "Argentina, 1915",
      "description": "Un pueblucho seco donde el comisario, los patrones y los favores políticos pesan más que la ley. Una banda peligrosa dice pelear contra la corrupción, aunque su justicia llega manchada de sangre.",
      "image": "mapa_pampa",
      "exclusive": "Payador",
      "roles": [
        {
          "id": "aldeano",
          "title": "Aldeano",
          "story": "Vive en un pueblucho donde el polvo entra por las ventanas y las noticias llegan tarde, si llegan. No espera justicia de nadie: ni del comisario, ni del patrón, ni del cura. Aprendió que sobrevivir también es saber cuándo cerrar la boca.",
          "image": "rol_aldeano_gaucho",
          "advice": "No tienes acción nocturna. Usa el debate: pregunta, compara versiones y recuerda quién acusó, defendió o cambió su historia.",
          "function": "No tiene habilidad especial. Participa en el debate y en las votaciones para descubrir a los traidores.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "policia",
          "title": "Comisario",
          "story": "No tiene oficina limpia ni placa respetada. Investiga entre pulperías, amenazas y expedientes que desaparecen cuando incomodan a alguien con poder. En este pueblo, encontrar la verdad es fácil; lo difícil es que alguien se anime a decirla.",
          "image": "rol_detective_gaucho",
          "advice": "Cada noche investiga a un jugador. Guarda tus pistas hasta que puedas usarlas sin exponerte demasiado pronto.",
          "function": "Cada noche investiga a un jugador y recibe una pista sobre si parece inocente o sospechoso.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "medico",
          "title": "Médica",
          "story": "Antes curaba heridas de hombres buscados por la ley, sin preguntar demasiado. Logró alejarse de esa vida, pero todavía reconoce el sonido de ciertos pasos en la puerta. Ahora cura al pueblo, aunque sabe que el pasado siempre vuelve montado y con sed.",
          "image": "rol_medico_gaucho",
          "advice": "Cada noche protege a un jugador. Puedes protegerte si necesitas sobrevivir, o cuidar a quien tenga información clave.",
          "function": "Cada noche protege a un jugador. Si ese jugador iba a morir, la eliminación se cancela.",
          "minimum": 5,
          "team": "Pueblo"
        },
        {
          "id": "alcalde",
          "title": "Alcaldesa",
          "story": "Gobierna poco y firma mucho. Entre comisarios corruptos, favores políticos y patrones que hablan más fuerte que la ley, intenta parecer autoridad en un pueblo donde todos saben quién manda de verdad.",
          "image": "rol_alcalde_gaucho",
          "advice": "Puedes revelarte durante el debate. Desde entonces tu voto vale doble y puedes decidir empates.",
          "function": "Puede revelar su identidad durante el debate. Desde ese momento su voto vale doble y decide entre los dos participantes más votados si hay empate.",
          "minimum": 8,
          "team": "Pueblo"
        },
        {
          "id": "asesino",
          "title": "Asesino",
          "story": "No mata por gloria ni por fe: mata porque la banda lo ordena y porque el miedo funciona mejor que cualquier discurso. Se cree parte de una justicia nueva, pero cada cuerpo que deja atrás lo acerca más a los mismos corruptos que dice odiar.",
          "image": "rol_asesino_gaucho",
          "advice": "Cada noche elige una víctima con los Traidores. De día, desvía sospechas sin defender siempre a tus aliados.",
          "function": "Los asesinos eligen en conjunto una víctima durante la noche. Si queda uno solo, decide por su cuenta.",
          "minimum": 5,
          "team": "Traidores"
        },
        {
          "id": "espia",
          "title": "Espía",
          "story": "Escucha detrás de mostradores, en patios de tierra y en mesas donde el vino afloja la lengua. Nadie le presta demasiada atención, y por eso mismo sabe más que todos. En un pueblo chico, el secreto siempre pasa por alguien.",
          "image": "rol_espia_gaucho",
          "advice": "El investigador te verá como inocente. Participa en la elección de víctima y usa esa apariencia para proteger a los Traidores.",
          "function": "Elige la víctima cada noche junto a los asesinos, pero ante la investigación aparece como inocente.",
          "minimum": 10,
          "team": "Traidores"
        },
        {
          "id": "mercenario",
          "title": "Mercenario",
          "story": "No pregunta si el trabajo es justo, solo cuánto pagan y quién queda parado al final. Ha servido a comisarios, bandidos y patrones con la misma cara cansada. Su moral dura lo mismo que una bolsa de monedas.",
          "image": "rol_mercenario_gaucho",
          "advice": "Cada noche silencia a un jugador. Elige a quien pueda convencer al pueblo o compartir información importante.",
          "function": "Forma parte del bando traidor. Puede impedir que una víctima hable o vote durante el día siguiente.",
          "minimum": 7,
          "team": "Traidores"
        },
        {
          "id": "desertor",
          "title": "Desertor",
          "story": "Perteneció a la banda el tiempo suficiente para entender que el código tenía letra chica. Se fue antes de terminar convertida en leyenda o cadáver. Desde entonces cambia de rumbo cada vez que escucha cascos acercarse.",
          "image": "rol_desertor_gaucho",
          "advice": "Elige un bando y ayuda a que gane. Sobrevivir importa: no te comprometas sin mirar quién tiene ventaja.",
          "function": "Elige un bando al comenzar. Puede reconsiderarlo una sola vez cuando quedan aproximadamente dos tercios de los jugadores iniciales y debe sobrevivir para ganar con su bando final.",
          "minimum": 14,
          "team": "Neutral"
        },
        {
          "id": "payador",
          "title": "Payador",
          "story": "Es el hazmerreír del pueblo, pero todos lo quieren un poco. Canta mal cuando está sobrio y peor cuando está inspirado, aunque sus coplas siempre terminan juntando gente.",
          "image": "rol_payador_gaucho",
          "advice": "No actúas de noche. De día puedes iniciar Contrapunto entre dos jugadores cuyas versiones se contradigan.",
          "function": "Una vez por partida elige dos participantes para un Contrapunto. Solo esos dos pueden hablar (el Payador escucha); al terminar señala a uno, que recibe un voto adicional.",
          "minimum": 8,
          "team": "Pueblo"
        }
      ]
    }
  ],
  "help": [
    {
      "id": "About",
      "title": "DE QUÉ TRATA",
      "body": "Traidores es un juego de deducción social, engaño y debate para 5 a 15 jugadores. Cada participante recibe un rol secreto. Algunos protegen al pueblo; otros intentan controlarlo desde las sombras; y ciertos neutrales persiguen una victoria propia.\n\nNo alcanza con descubrir la verdad: también hay que lograr que los demás te crean."
    },
    {
      "id": "How",
      "title": "CÓMO SE JUEGA",
      "body": "1. ROL SECRETO\nLee tu carta y recordá tu objetivo. No se la muestres a nadie.\n\n2. NOCHE\nEl pueblo duerme. Los roles nocturnos actúan en secreto: los Traidores atacan, el Detective investiga, el Médico protege y otros roles usan sus habilidades.\n\n3. AMANECER Y DEBATE\nSe anuncia lo ocurrido. Los sobrevivientes preguntan, acusan, se defienden y forman alianzas.\n\n4. VOTACIÓN\nCada jugador habilitado elige a un sospechoso. El resultado puede expulsar a un jugador o activar una condición especial.\n\n5. NUEVA RONDA\nSi ningún bando alcanzó su victoria, vuelve a caer la noche."
    },
    {
      "id": "Modes",
      "title": "LOCAL U ONLINE",
      "body": "JUGAR vs IA\nEntrás solo, elegís mapa y cantidad de participantes, y el resto de la mesa es controlado por la IA. Es la mejor forma de practicar roles y aprender el ritmo.\n\nJUGAR EN LÍNEA\nLas partidas normales son para 5 a 15 personas. Una sala pública aparece en Buscar partida; una privada se comparte mediante su código. El anfitrión configura la mesa y todos deben marcar LISTO antes de comenzar.\n\nSi se corta la conexión, volvé a Jugar en línea: la app intentará recuperar tu sala activa."
    },
    {
      "id": "Controls",
      "title": "CONTROLES ESENCIALES",
      "body": "- Leé el cartel central: indica la fase y qué espera el juego de vos.\n\n- Usá VER CARTA para recordar tu rol sin mostrar la pantalla.\n\n- En la votación, un toque registra tu voto. Podés cambiarlo tocando otra carta hasta que cierre el tiempo. Las habilidades nocturnas sí se confirman con el botón de acción.\n\n- El chat público sirve para debatir. Algunos roles o estados habilitan canales privados.\n\n- Tocá la carta de otro jugador para consultar su perfil. En online también podés silenciar para vos su chat y sus emotes.\n\n- Desde el engranaje podés consultar opciones o abandonar la partida de forma segura."
    },
    {
      "id": "Win",
      "title": "CÓMO SE GANA",
      "body": "PUEBLO\nGana cuando ya no queda ningún Asesino capaz de matar.\n\nTRAIDORES\nGanan cuando igualan o superan en número a los jugadores del bando del Pueblo. Los neutrales no entran en esa cuenta.\n\nBUFÓN (neutral)\nObtiene su victoria especial si el pueblo lo expulsa durante una votación. La partida principal continúa.\n\nDESERTOR (neutral)\nDebe sobrevivir y conseguir que gane el bando que eligió finalmente."
    },
    {
      "id": "Deception",
      "title": "EL ENGAÑO ES PARTE DEL JUEGO",
      "body": "Se permite mentir sobre tu rol, inventar una investigación, negar una acción, acusar para desviar sospechas o fingir que tienes información.\n\nLo que no se permite es mostrar la pantalla, enseñar la carta o usar información externa para demostrar que dices la verdad. Convencer debe depender de tus palabras y de lo ocurrido dentro de la partida."
    },
    {
      "id": "Community",
      "title": "NORMAS Y SEGURIDAD ONLINE",
      "body": "JUGÁ CON RESPETO\nEl engaño pertenece a la partida; los ataques personales, no. No se permiten insultos, amenazas, acoso, discriminación, contenido sexual, datos personales, spam, trampas ni suplantación.\n\nSILENCIAR PARA MÍ\nOculta solamente en tu dispositivo el chat y los emotes de esa persona. Es personal, inmediato y reversible.\n\nSILENCIO DE MESA\nEs una mecánica temporal que votan los jugadores vivos. Limita el texto libre, pero no equivale a un castigo de moderación.\n\nREPORTAR\nEnvía el caso para revisión. No expulsa automáticamente y debe usarse de buena fe.\n\nEXPULSAR O BLOQUEAR ESTA SALA\nSólo el anfitrión puede hacerlo. Expulsar saca al jugador; bloquear además impide que reingrese a esa sala. No es un bloqueo global de la cuenta."
    },
    {
      "id": "Rules",
      "title": "REGLAS IMPORTANTES",
      "body": "- Tu rol es secreto hasta que una regla indique lo contrario.\n\n- Los jugadores eliminados no hablan ni votan. La excepción es una voz invocada por el Oráculo: puede debatir, pero no votar ni usar habilidades.\n\n- Un jugador silenciado no puede hablar ni votar durante ese día.\n\n- El Alcalde revelado tiene voto doble y puede resolver ciertos empates.\n\n- Las habilidades de uso único no se recuperan en la ronda siguiente.\n\n- Mentir dentro del juego está permitido; insultar, molestar fuera del personaje o atacar personalmente a otro jugador, no."
    },
    {
      "id": "Tips",
      "title": "CONSEJOS GENERALES",
      "body": "- Presta atención a quién acusa primero y quién cambia de versión.\n\n- No reveles información privada sin pensar quién puede protegerte.\n\n- Hablar mucho no demuestra inocencia, pero guardar silencio tampoco.\n\n- Un aliado puede equivocarse y un enemigo puede decir la verdad.\n\n- Recordá las votaciones anteriores: suelen revelar alianzas mejor que los discursos."
    },
    {
      "id": "Roles",
      "title": "CONSEJOS POR ROL",
      "body": ""
    }
  ],
  "tutorial": [
    {
      "id": "role",
      "title": "TU ROL ES SECRETO",
      "body": "Cada participante recibe una carta con un bando, una habilidad y una condición de victoria.",
      "hint": "Leela con atención y no muestres la pantalla. Podés mentir para protegerte, pero nadie debe usar información de afuera del juego."
    },
    {
      "id": "night",
      "title": "ACTUÁ EN LA NOCHE",
      "body": "Cuando sea tu turno, el cartel central te dirá qué hacer. Elegí un objetivo y confirmá antes de que termine el tiempo.",
      "hint": "Si tu rol no actúa en esa fase, observá la mesa y esperá el amanecer."
    },
    {
      "id": "debate",
      "title": "ESCUCHÁ Y CONVENCÉ",
      "body": "Durante el día, compará versiones, preguntá, acusá y defendete. El chat y lo ocurrido en rondas anteriores son tus mejores pistas.",
      "hint": "Decir la verdad no alcanza: también tenés que lograr que el pueblo te crea."
    },
    {
      "id": "vote",
      "title": "VOTÁ Y SOBREVIVÍ",
      "body": "Tocá la carta de tu sospechoso para votar. Si cambiás de opinión, podés tocar otra carta hasta que cierre la votación. La partida continúa hasta que un bando cumpla su objetivo.",
      "hint": "Para practicar sin presión, empezá en JUGAR vs IA. Podés repetir este tutorial desde AYUDA."
    }
  ],
  "achievements": [
    {
      "id": "profile_created",
      "title": "Te agradezco infinitamente",
      "shortTitle": "Gracias",
      "description": "Te registraste en Traidores y dejaste tu nombre grabado en el pueblo.",
      "rarity": "BRONZE"
    },
    {
      "id": "assassin_kills_25",
      "title": "Ser primero no es lo importante, es lo unico",
      "shortTitle": "Primero",
      "description": "Mataste a 25 jugadores siendo Asesino. No era una carrera, pero igual llegaste primero.",
      "rarity": "BRONZE"
    },
    {
      "id": "jester_wins_5",
      "title": "Y me gusta el rol, el maldito rol!",
      "shortTitle": "Maldito rol",
      "description": "Ganaste 5 partidas como Bufón. Te votaron, te festejaron y encima te salió bien.",
      "rarity": "BRONZE"
    },
    {
      "id": "expel_all_killers",
      "title": "Hoy dormis afuera",
      "shortTitle": "Afuera",
      "description": "Expulsaste a todos los Asesinos de forma seguida durante el dia.",
      "rarity": "BRONZE"
    },
    {
      "id": "deserter_wins_10",
      "title": "Lo que no te mata, te infecta",
      "shortTitle": "Infecta",
      "description": "Ganaste 10 partidas como Desertor. Cambiaste de bando, pero nunca de objetivo.",
      "rarity": "BRONZE"
    },
    {
      "id": "mercenary_same_target_3",
      "title": "Ya nadie va a escuchar tu voto",
      "shortTitle": "Sin voto",
      "description": "Silenciaste a un mismo jugador 3 veces en una misma partida como Mercenario.",
      "rarity": "SILVER"
    },
    {
      "id": "villager_survives_12",
      "title": "Sobreviviendo dije, sobreviviendo",
      "shortTitle": "Sobreviviendo",
      "description": "Ganaste como Aldeano, sin morir, en una partida de mas de 12 jugadores.",
      "rarity": "SILVER"
    },
    {
      "id": "mayor_power_wins_15",
      "title": "El alcalde que fue prometido",
      "shortTitle": "Prometido",
      "description": "Ganaste 15 partidas como Alcalde despues de usar tu poder para decidir una expulsion.",
      "rarity": "SILVER"
    },
    {
      "id": "total_wins_50",
      "title": "Quien te ha visto y quien te ve",
      "shortTitle": "50 victorias",
      "description": "Ganaste 50 partidas. El pueblo ya no sabe si confiarte el mate o revisarte los bolsillos.",
      "rarity": "GOLD"
    },
    {
      "id": "traidores_supremo",
      "title": "Traidores Supremo",
      "shortTitle": "Supremo",
      "description": "Obtuviste todos los demas logros. A esta altura, el pueblo te saluda con respeto y miedo.",
      "rarity": "GOLD"
    }
  ],
  "emotes": [
    {
      "id": "griego_enojado",
      "title": "Enojado",
      "description": "Cuando la mesa te saca de quicio.",
      "theme": "Aldeano griego",
      "image": "reaction_angry",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "griego_triste",
      "title": "Triste",
      "description": "Para una traición que dolió.",
      "theme": "Aldeano griego",
      "image": "reaction_sad",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "griego_contento",
      "title": "Contento",
      "description": "Todo salió demasiado bien.",
      "theme": "Aldeano griego",
      "image": "reaction_happy",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "griego_sospechoso",
      "title": "Sospechoso",
      "description": "Algo acá no cierra.",
      "theme": "Aldeano griego",
      "image": "reaction_suspicious",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "medieval_enojado",
      "title": "Enojado",
      "description": "Cuando la mesa te saca de quicio.",
      "theme": "Asesino medieval",
      "image": "reaction_assassin_medieval_angry",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "medieval_triste",
      "title": "Triste",
      "description": "Para una traición que dolió.",
      "theme": "Asesino medieval",
      "image": "reaction_assassin_medieval_sad",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "medieval_contento",
      "title": "Contento",
      "description": "Todo salió demasiado bien.",
      "theme": "Asesino medieval",
      "image": "reaction_assassin_medieval_happy",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "medieval_sospechoso",
      "title": "Sospechoso",
      "description": "Algo acá no cierra.",
      "theme": "Asesino medieval",
      "image": "reaction_assassin_medieval_suspicious",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "gaucho_enojado",
      "title": "Enojado",
      "description": "Cuando la mesa te saca de quicio.",
      "theme": "Detective gaucho",
      "image": "reaction_detective_gaucho_angry",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "gaucho_triste",
      "title": "Triste",
      "description": "Para una traición que dolió.",
      "theme": "Detective gaucho",
      "image": "reaction_detective_gaucho_sad",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "gaucho_contento",
      "title": "Contento",
      "description": "Todo salió demasiado bien.",
      "theme": "Detective gaucho",
      "image": "reaction_detective_gaucho_happy",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "gaucho_sospechoso",
      "title": "Sospechoso",
      "description": "Algo acá no cierra.",
      "theme": "Detective gaucho",
      "image": "reaction_detective_gaucho_suspicious",
      "category": "CLASSIC",
      "premium": false,
      "animated": false
    },
    {
      "id": "premium_hermosa_manana",
      "title": "Hermosa mañana verdad?",
      "description": "Un amanecer sospechosamente tranquilo.",
      "theme": "Premium",
      "image": "reaction_premium_hermosa_manana",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_mate",
      "title": "Ruidito de mate",
      "description": "Para mirar el caos con mate en mano.",
      "theme": "Premium",
      "image": "reaction_premium_mate",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_dormida",
      "title": "Me duermo zzz",
      "description": "Cuando el debate no arranca.",
      "theme": "Premium",
      "image": "reaction_premium_dormida",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_genio",
      "title": "Genio",
      "description": "¿Hace falta decirlo?",
      "theme": "Premium",
      "image": "reaction_premium_genio",
      "category": "LEGENDARY",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_medico_timido",
      "title": "Médico tímido",
      "description": "Yo no fui… ¿o sí?",
      "theme": "Premium",
      "image": "reaction_premium_medico_timido",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_desertor_lengua",
      "title": "Cualquiera",
      "description": "Cuando la partida ya es cualquier cosa.",
      "theme": "Premium",
      "image": "reaction_premium_desertor_lengua",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_oraculo_mmm_nie",
      "title": "Mmmm... ñe",
      "description": "Una respuesta sin argumentos, pero contundente.",
      "theme": "Premium",
      "image": "reaction_premium_oraculo_mmm_nie",
      "category": "MEME",
      "premium": true,
      "animated": false
    },
    {
      "id": "premium_six_seven",
      "title": "6 7",
      "description": "Seis, siete. No hace falta entenderlo.",
      "theme": "Premium",
      "image": "reaction_premium_six_seven",
      "category": "LEGENDARY",
      "premium": true,
      "animated": true
    }
  ]
}
"""#
}
